---
name: Cache-Funcky
version: 0.0.2
author:
  - 'Masahiro Funakoshi <masap@cpan.org>'
abstract: 'How is simple, convenient cache module?'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  UNIVERSAL::require: 0
  version: 0
provides:
  Cache::Funcky:
    file: lib/Cache/Funcky.pm
    version: !!perl/hash:version
      original: 0.0.2
      qv: 1
      version:
        - 0
        - 0
        - 2
  Cache::Funcky::Storage:
    file: lib/Cache/Funcky/Storage.pm
  Cache::Funcky::Storage::Simple:
    file: lib/Cache/Funcky/Storage/Simple.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
